/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sematext.cloud.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DailyDto
 */


public class DailyDto {
  @SerializedName("day")
  private Long day = null;

  @SerializedName("failed")
  private Long failed = null;

  @SerializedName("ingestedCount")
  private Long ingestedCount = null;

  @SerializedName("ingestedVolume")
  private Long ingestedVolume = null;

  @SerializedName("storedCount")
  private Long storedCount = null;

  @SerializedName("storedVolume")
  private Long storedVolume = null;

  public DailyDto day(Long day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @Schema(description = "")
  public Long getDay() {
    return day;
  }

  public void setDay(Long day) {
    this.day = day;
  }

  public DailyDto failed(Long failed) {
    this.failed = failed;
    return this;
  }

   /**
   * Get failed
   * @return failed
  **/
  @Schema(description = "")
  public Long getFailed() {
    return failed;
  }

  public void setFailed(Long failed) {
    this.failed = failed;
  }

  public DailyDto ingestedCount(Long ingestedCount) {
    this.ingestedCount = ingestedCount;
    return this;
  }

   /**
   * Get ingestedCount
   * @return ingestedCount
  **/
  @Schema(description = "")
  public Long getIngestedCount() {
    return ingestedCount;
  }

  public void setIngestedCount(Long ingestedCount) {
    this.ingestedCount = ingestedCount;
  }

  public DailyDto ingestedVolume(Long ingestedVolume) {
    this.ingestedVolume = ingestedVolume;
    return this;
  }

   /**
   * Get ingestedVolume
   * @return ingestedVolume
  **/
  @Schema(description = "")
  public Long getIngestedVolume() {
    return ingestedVolume;
  }

  public void setIngestedVolume(Long ingestedVolume) {
    this.ingestedVolume = ingestedVolume;
  }

  public DailyDto storedCount(Long storedCount) {
    this.storedCount = storedCount;
    return this;
  }

   /**
   * Get storedCount
   * @return storedCount
  **/
  @Schema(description = "")
  public Long getStoredCount() {
    return storedCount;
  }

  public void setStoredCount(Long storedCount) {
    this.storedCount = storedCount;
  }

  public DailyDto storedVolume(Long storedVolume) {
    this.storedVolume = storedVolume;
    return this;
  }

   /**
   * Get storedVolume
   * @return storedVolume
  **/
  @Schema(description = "")
  public Long getStoredVolume() {
    return storedVolume;
  }

  public void setStoredVolume(Long storedVolume) {
    this.storedVolume = storedVolume;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DailyDto dailyDto = (DailyDto) o;
    return Objects.equals(this.day, dailyDto.day) &&
        Objects.equals(this.failed, dailyDto.failed) &&
        Objects.equals(this.ingestedCount, dailyDto.ingestedCount) &&
        Objects.equals(this.ingestedVolume, dailyDto.ingestedVolume) &&
        Objects.equals(this.storedCount, dailyDto.storedCount) &&
        Objects.equals(this.storedVolume, dailyDto.storedVolume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(day, failed, ingestedCount, ingestedVolume, storedCount, storedVolume);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DailyDto {\n");
    
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    ingestedCount: ").append(toIndentedString(ingestedCount)).append("\n");
    sb.append("    ingestedVolume: ").append(toIndentedString(ingestedVolume)).append("\n");
    sb.append("    storedCount: ").append(toIndentedString(storedCount)).append("\n");
    sb.append("    storedVolume: ").append(toIndentedString(storedVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
