/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sematext.cloud.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sematext.cloud.model.AlertNotification;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * NotificationsResponseEntry
 */


public class NotificationsResponseEntry {
  @SerializedName("end")
  private String end = null;

  @SerializedName("notifications")
  private List<AlertNotification> notifications = null;

  @SerializedName("start")
  private String start = null;

  public NotificationsResponseEntry end(String end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @Schema(description = "")
  public String getEnd() {
    return end;
  }

  public void setEnd(String end) {
    this.end = end;
  }

  public NotificationsResponseEntry notifications(List<AlertNotification> notifications) {
    this.notifications = notifications;
    return this;
  }

  public NotificationsResponseEntry addNotificationsItem(AlertNotification notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/
  @Schema(description = "")
  public List<AlertNotification> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<AlertNotification> notifications) {
    this.notifications = notifications;
  }

  public NotificationsResponseEntry start(String start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public String getStart() {
    return start;
  }

  public void setStart(String start) {
    this.start = start;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationsResponseEntry notificationsResponseEntry = (NotificationsResponseEntry) o;
    return Objects.equals(this.end, notificationsResponseEntry.end) &&
        Objects.equals(this.notifications, notificationsResponseEntry.notifications) &&
        Objects.equals(this.start, notificationsResponseEntry.start);
  }

  @Override
  public int hashCode() {
    return Objects.hash(end, notifications, start);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationsResponseEntry {\n");
    
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
