/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sematext.cloud.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ServiceIntegration
 */

public class ServiceIntegration {
  @SerializedName("appTypeId")
  private Long appTypeId = null;

  @SerializedName("appTypeName")
  private String appTypeName = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("externalProductId")
  private Long externalProductId = null;

  @SerializedName("externalProductName")
  private String externalProductName = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("integrationType")
  private String integrationType = null;

  @SerializedName("ordinal")
  private Integer ordinal = null;

  @SerializedName("parentIntegrationId")
  private Long parentIntegrationId = null;

  @SerializedName("sematextService")
  private String sematextService = null;

  @SerializedName("visible")
  private Boolean visible = null;

  public ServiceIntegration appTypeId(Long appTypeId) {
    this.appTypeId = appTypeId;
    return this;
  }

   /**
   * Get appTypeId
   * @return appTypeId
  **/
  @ApiModelProperty(value = "")
  public Long getAppTypeId() {
    return appTypeId;
  }

  public void setAppTypeId(Long appTypeId) {
    this.appTypeId = appTypeId;
  }

  public ServiceIntegration appTypeName(String appTypeName) {
    this.appTypeName = appTypeName;
    return this;
  }

   /**
   * Get appTypeName
   * @return appTypeName
  **/
  @ApiModelProperty(value = "")
  public String getAppTypeName() {
    return appTypeName;
  }

  public void setAppTypeName(String appTypeName) {
    this.appTypeName = appTypeName;
  }

  public ServiceIntegration displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ServiceIntegration enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public ServiceIntegration externalProductId(Long externalProductId) {
    this.externalProductId = externalProductId;
    return this;
  }

   /**
   * Get externalProductId
   * @return externalProductId
  **/
  @ApiModelProperty(value = "")
  public Long getExternalProductId() {
    return externalProductId;
  }

  public void setExternalProductId(Long externalProductId) {
    this.externalProductId = externalProductId;
  }

  public ServiceIntegration externalProductName(String externalProductName) {
    this.externalProductName = externalProductName;
    return this;
  }

   /**
   * Get externalProductName
   * @return externalProductName
  **/
  @ApiModelProperty(value = "")
  public String getExternalProductName() {
    return externalProductName;
  }

  public void setExternalProductName(String externalProductName) {
    this.externalProductName = externalProductName;
  }

  public ServiceIntegration id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ServiceIntegration integrationType(String integrationType) {
    this.integrationType = integrationType;
    return this;
  }

   /**
   * Get integrationType
   * @return integrationType
  **/
  @ApiModelProperty(value = "")
  public String getIntegrationType() {
    return integrationType;
  }

  public void setIntegrationType(String integrationType) {
    this.integrationType = integrationType;
  }

  public ServiceIntegration ordinal(Integer ordinal) {
    this.ordinal = ordinal;
    return this;
  }

   /**
   * Get ordinal
   * @return ordinal
  **/
  @ApiModelProperty(value = "")
  public Integer getOrdinal() {
    return ordinal;
  }

  public void setOrdinal(Integer ordinal) {
    this.ordinal = ordinal;
  }

  public ServiceIntegration parentIntegrationId(Long parentIntegrationId) {
    this.parentIntegrationId = parentIntegrationId;
    return this;
  }

   /**
   * Get parentIntegrationId
   * @return parentIntegrationId
  **/
  @ApiModelProperty(value = "")
  public Long getParentIntegrationId() {
    return parentIntegrationId;
  }

  public void setParentIntegrationId(Long parentIntegrationId) {
    this.parentIntegrationId = parentIntegrationId;
  }

  public ServiceIntegration sematextService(String sematextService) {
    this.sematextService = sematextService;
    return this;
  }

   /**
   * Get sematextService
   * @return sematextService
  **/
  @ApiModelProperty(value = "")
  public String getSematextService() {
    return sematextService;
  }

  public void setSematextService(String sematextService) {
    this.sematextService = sematextService;
  }

  public ServiceIntegration visible(Boolean visible) {
    this.visible = visible;
    return this;
  }

   /**
   * Get visible
   * @return visible
  **/
  @ApiModelProperty(value = "")
  public Boolean isVisible() {
    return visible;
  }

  public void setVisible(Boolean visible) {
    this.visible = visible;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceIntegration serviceIntegration = (ServiceIntegration) o;
    return Objects.equals(this.appTypeId, serviceIntegration.appTypeId) &&
        Objects.equals(this.appTypeName, serviceIntegration.appTypeName) &&
        Objects.equals(this.displayName, serviceIntegration.displayName) &&
        Objects.equals(this.enabled, serviceIntegration.enabled) &&
        Objects.equals(this.externalProductId, serviceIntegration.externalProductId) &&
        Objects.equals(this.externalProductName, serviceIntegration.externalProductName) &&
        Objects.equals(this.id, serviceIntegration.id) &&
        Objects.equals(this.integrationType, serviceIntegration.integrationType) &&
        Objects.equals(this.ordinal, serviceIntegration.ordinal) &&
        Objects.equals(this.parentIntegrationId, serviceIntegration.parentIntegrationId) &&
        Objects.equals(this.sematextService, serviceIntegration.sematextService) &&
        Objects.equals(this.visible, serviceIntegration.visible);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appTypeId, appTypeName, displayName, enabled, externalProductId, externalProductName, id, integrationType, ordinal, parentIntegrationId, sematextService, visible);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceIntegration {\n");
    
    sb.append("    appTypeId: ").append(toIndentedString(appTypeId)).append("\n");
    sb.append("    appTypeName: ").append(toIndentedString(appTypeName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    externalProductId: ").append(toIndentedString(externalProductId)).append("\n");
    sb.append("    externalProductName: ").append(toIndentedString(externalProductName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    integrationType: ").append(toIndentedString(integrationType)).append("\n");
    sb.append("    ordinal: ").append(toIndentedString(ordinal)).append("\n");
    sb.append("    parentIntegrationId: ").append(toIndentedString(parentIntegrationId)).append("\n");
    sb.append("    sematextService: ").append(toIndentedString(sematextService)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

