/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sematext.cloud.client;

import com.sematext.cloud.ApiException;
import com.sematext.cloud.model.AlertNotificationRequest;
import com.sematext.cloud.model.GenericApiResponse;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for AlertNotificationsApi
 */
@Ignore
public class AlertNotificationsApiTest {

    private final AlertNotificationsApi api = new AlertNotificationsApi();

    /**
     * Get alert notifications for an app
     *
     * Default value of interval is 1d
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAlertNotificationsForAppUsingPOST1Test() throws ApiException {
        Long appId = null;
        AlertNotificationRequest timeInterval = null;
        GenericApiResponse response = api.getAlertNotificationsForAppUsingPOST1(appId, timeInterval);

        // TODO: test validations
    }

    /**
     * Get alert notifications for a user
     *
     * Default value of interval is 1d
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAlertNotificationsForUserUsingPOSTTest() throws ApiException {
        AlertNotificationRequest timeInterval = null;
        GenericApiResponse response = api.getAlertNotificationsForUserUsingPOST(timeInterval);

        // TODO: test validations
    }

}
