/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sematext.cloud.client;

import com.sematext.cloud.model.BillingInfo;
import com.sematext.cloud.model.InvoiceResponse;
import com.sematext.cloud.model.PlansResponse;
import com.sematext.cloud.model.UpdatePlanResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for BillingApi
 */
@Ignore
public class BillingApiTest {

    private final BillingApi api = new BillingApi();

    /**
     * Get invoice details
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDetailedInvoiceUsingGETTest() throws Exception {
        String service = null;
        Integer year = null;
        Integer month = null;
        InvoiceResponse response = api.getDetailedInvoiceUsingGET(service, year, month);

        // TODO: test validations
    }
    /**
     * Get available plans
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAvailablePlansUsingGET1Test() throws Exception {
        Long integrationId = null;
        String appType = null;
        PlansResponse response = api.listAvailablePlansUsingGET1(integrationId, appType);

        // TODO: test validations
    }
    /**
     * Update plan for an app
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updatePlanUsingPUTTest() throws Exception {
        BillingInfo body = null;
        Long appId = null;
        UpdatePlanResponse response = api.updatePlanUsingPUT(body, appId);

        // TODO: test validations
    }
}
