/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sematext.cloud.client;

import com.sematext.cloud.ApiException;
import com.sematext.cloud.model.DataSeriesRequest;
import com.sematext.cloud.model.GenericApiResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MetricsApi
 */
@Ignore
public class MetricsApiTest {

    private final MetricsApi api = new MetricsApi();


    /**
     * Get metrics data points for an app
     *
     * Default value of interval is 5m
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDataSeriesUsingPOST1Test() throws ApiException {
        Long appId = null;
        DataSeriesRequest requestBody = null;
        GenericApiResponse response = api.listDataSeriesUsingPOST1(appId, requestBody);

        // TODO: test validations
    }

    /**
     * Get metrics filters and their values for an app
     *
     * Default value of interval is 5m
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFiltersUsingPOST1Test() throws ApiException {
        Long appId = null;
        DataSeriesRequest requestBody = null;
        GenericApiResponse response = api.listFiltersUsingPOST1(appId, requestBody);

        // TODO: test validations
    }

    /**
     * Get metrics keys for an app
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMetricsKeysUsingGET1Test() throws ApiException {
        Long appId = null;
        GenericApiResponse response = api.listMetricsKeysUsingGET1(appId);

        // TODO: test validations
    }

    /**
     * Get metrics info for an app
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMetricsUsingGETTest() throws ApiException {
        Long appId = null;
        GenericApiResponse response = api.listMetricsUsingGET(appId);

        // TODO: test validations
    }

}
