/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sematext.cloud.client;

import com.sematext.cloud.ApiException;
import com.sematext.cloud.model.GenericApiResponse;
import com.sematext.cloud.model.ReportInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionsApi
 */
@Ignore
public class SubscriptionsApiTest {

    private final SubscriptionsApi api = new SubscriptionsApi();

    
    /**
     * Get subscriptions for an app
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGET2Test() throws ApiException {
        Long appId = null;
        GenericApiResponse response = api.listUsingGET2(appId);

        // TODO: test validations
    }
    
    /**
     * Trigger emailing of report for an app
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendReportUsingPOST1Test() throws ApiException {
        Long appId = null;
        ReportInfo emailDto = null;
        GenericApiResponse response = api.sendReportUsingPOST1(appId, emailDto);

        // TODO: test validations
    }
    
}
