/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sematext.cloud.client;

import com.sematext.cloud.ApiException;
import com.sematext.cloud.model.GenericApiResponse;
import com.sematext.cloud.model.ReportInfo;
import com.sematext.cloud.model.SubscriptionDashboardDto;
import com.sematext.cloud.model.SubscriptionDto;
import com.sematext.cloud.model.UpdateSubscriptionDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionsApi
 */
@Ignore
public class SubscriptionsApiTest {

    private final SubscriptionsApi api = new SubscriptionsApi();

    
    /**
     * Create App subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createForAppUsingPOST1Test() throws ApiException {
        Long appId = null;
        SubscriptionDto subscription = null;
        GenericApiResponse response = api.createForAppUsingPOST1(appId, subscription);

        // TODO: test validations
    }
    
    /**
     * Create dashboard subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createForDashUsingPOST1Test() throws ApiException {
        Long dashId = null;
        SubscriptionDashboardDto subscription = null;
        GenericApiResponse response = api.createForDashUsingPOST1(dashId, subscription);

        // TODO: test validations
    }
    
    /**
     * Delete subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUsingDELETE2Test() throws ApiException {
        Long updateableSubscriptionId = null;
        GenericApiResponse response = api.deleteUsingDELETE2(updateableSubscriptionId);

        // TODO: test validations
    }
    
    /**
     * Get subscriptions for an App
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGET2Test() throws ApiException {
        Long appId = null;
        GenericApiResponse response = api.listUsingGET2(appId);

        // TODO: test validations
    }
    
    /**
     * Get current account&#39;s subscriptions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGET4Test() throws ApiException {
        GenericApiResponse response = api.listUsingGET4();

        // TODO: test validations
    }
    
    /**
     * Email an App report
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendAppReportUsingPOST1Test() throws ApiException {
        Long appId = null;
        ReportInfo emailDto = null;
        GenericApiResponse response = api.sendAppReportUsingPOST1(appId, emailDto);

        // TODO: test validations
    }
    
    /**
     * Email a dashboard report
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendDashReportUsingPOSTTest() throws ApiException {
        Long dashId = null;
        ReportInfo emailDto = null;
        GenericApiResponse response = api.sendDashReportUsingPOST(dashId, emailDto);

        // TODO: test validations
    }
    
    /**
     * Toggle subscription status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void toggleEnabledUsingPUTTest() throws ApiException {
        Long updateableSubscriptionId = null;
        UpdateSubscriptionDto dto = null;
        GenericApiResponse response = api.toggleEnabledUsingPUT(updateableSubscriptionId, dto);

        // TODO: test validations
    }
    
    /**
     * Update App subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateForAppUsingPUT1Test() throws ApiException {
        Long appId = null;
        SubscriptionDto subscription = null;
        GenericApiResponse response = api.updateForAppUsingPUT1(appId, subscription);

        // TODO: test validations
    }
    
    /**
     * Update dashboard subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateForDashUsingPUT1Test() throws ApiException {
        Long dashId = null;
        SubscriptionDashboardDto subscription = null;
        GenericApiResponse response = api.updateForDashUsingPUT1(dashId, subscription);

        // TODO: test validations
    }
    
}
