/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sematext.stcloud.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sematext.stcloud.model.AlertRule;
import com.sematext.stcloud.model.UserPermissions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SavedQuery
 */

public class SavedQuery {
  @SerializedName("alertRule")
  private AlertRule alertRule = null;

  @SerializedName("allowModification")
  private Boolean allowModification = null;

  @SerializedName("applicationId")
  private String applicationId = null;

  @SerializedName("applicationName")
  private String applicationName = null;

  @SerializedName("applicationToken")
  private String applicationToken = null;

  @SerializedName("creatorEmail")
  private String creatorEmail = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("labelColor")
  private String labelColor = null;

  @SerializedName("logseneAlertType")
  private Object logseneAlertType = null;

  @SerializedName("ownerEmail")
  private String ownerEmail = null;

  @SerializedName("queryName")
  private String queryName = null;

  @SerializedName("queryString")
  private String queryString = null;

  @SerializedName("userPermissions")
  private UserPermissions userPermissions = null;

  public SavedQuery alertRule(AlertRule alertRule) {
    this.alertRule = alertRule;
    return this;
  }

   /**
   * Get alertRule
   * @return alertRule
  **/
  @ApiModelProperty(value = "")
  public AlertRule getAlertRule() {
    return alertRule;
  }

  public void setAlertRule(AlertRule alertRule) {
    this.alertRule = alertRule;
  }

   /**
   * Get allowModification
   * @return allowModification
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isAllowModification() {
    return allowModification;
  }

  public SavedQuery applicationId(String applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @ApiModelProperty(value = "")
  public String getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(String applicationId) {
    this.applicationId = applicationId;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @ApiModelProperty(value = "")
  public String getApplicationName() {
    return applicationName;
  }

   /**
   * Get applicationToken
   * @return applicationToken
  **/
  @ApiModelProperty(value = "")
  public String getApplicationToken() {
    return applicationToken;
  }

   /**
   * Get creatorEmail
   * @return creatorEmail
  **/
  @ApiModelProperty(value = "")
  public String getCreatorEmail() {
    return creatorEmail;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public SavedQuery labelColor(String labelColor) {
    this.labelColor = labelColor;
    return this;
  }

   /**
   * Get labelColor
   * @return labelColor
  **/
  @ApiModelProperty(value = "")
  public String getLabelColor() {
    return labelColor;
  }

  public void setLabelColor(String labelColor) {
    this.labelColor = labelColor;
  }

  public SavedQuery logseneAlertType(Object logseneAlertType) {
    this.logseneAlertType = logseneAlertType;
    return this;
  }

   /**
   * Get logseneAlertType
   * @return logseneAlertType
  **/
  @ApiModelProperty(value = "")
  public Object getLogseneAlertType() {
    return logseneAlertType;
  }

  public void setLogseneAlertType(Object logseneAlertType) {
    this.logseneAlertType = logseneAlertType;
  }

   /**
   * Get ownerEmail
   * @return ownerEmail
  **/
  @ApiModelProperty(value = "")
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public SavedQuery queryName(String queryName) {
    this.queryName = queryName;
    return this;
  }

   /**
   * Get queryName
   * @return queryName
  **/
  @ApiModelProperty(value = "")
  public String getQueryName() {
    return queryName;
  }

  public void setQueryName(String queryName) {
    this.queryName = queryName;
  }

  public SavedQuery queryString(String queryString) {
    this.queryString = queryString;
    return this;
  }

   /**
   * Get queryString
   * @return queryString
  **/
  @ApiModelProperty(value = "")
  public String getQueryString() {
    return queryString;
  }

  public void setQueryString(String queryString) {
    this.queryString = queryString;
  }

  public SavedQuery userPermissions(UserPermissions userPermissions) {
    this.userPermissions = userPermissions;
    return this;
  }

   /**
   * Get userPermissions
   * @return userPermissions
  **/
  @ApiModelProperty(value = "")
  public UserPermissions getUserPermissions() {
    return userPermissions;
  }

  public void setUserPermissions(UserPermissions userPermissions) {
    this.userPermissions = userPermissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SavedQuery savedQuery = (SavedQuery) o;
    return Objects.equals(this.alertRule, savedQuery.alertRule) &&
        Objects.equals(this.allowModification, savedQuery.allowModification) &&
        Objects.equals(this.applicationId, savedQuery.applicationId) &&
        Objects.equals(this.applicationName, savedQuery.applicationName) &&
        Objects.equals(this.applicationToken, savedQuery.applicationToken) &&
        Objects.equals(this.creatorEmail, savedQuery.creatorEmail) &&
        Objects.equals(this.id, savedQuery.id) &&
        Objects.equals(this.labelColor, savedQuery.labelColor) &&
        Objects.equals(this.logseneAlertType, savedQuery.logseneAlertType) &&
        Objects.equals(this.ownerEmail, savedQuery.ownerEmail) &&
        Objects.equals(this.queryName, savedQuery.queryName) &&
        Objects.equals(this.queryString, savedQuery.queryString) &&
        Objects.equals(this.userPermissions, savedQuery.userPermissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alertRule, allowModification, applicationId, applicationName, applicationToken, creatorEmail, id, labelColor, logseneAlertType, ownerEmail, queryName, queryString, userPermissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SavedQuery {\n");
    
    sb.append("    alertRule: ").append(toIndentedString(alertRule)).append("\n");
    sb.append("    allowModification: ").append(toIndentedString(allowModification)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    applicationToken: ").append(toIndentedString(applicationToken)).append("\n");
    sb.append("    creatorEmail: ").append(toIndentedString(creatorEmail)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labelColor: ").append(toIndentedString(labelColor)).append("\n");
    sb.append("    logseneAlertType: ").append(toIndentedString(logseneAlertType)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    queryName: ").append(toIndentedString(queryName)).append("\n");
    sb.append("    queryString: ").append(toIndentedString(queryString)).append("\n");
    sb.append("    userPermissions: ").append(toIndentedString(userPermissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

