/*
 * Sematext Cloud API
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BasicAuthMethodDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BasicOrganizationDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-02T03:09:37.790+12:00")
public class BasicOrganizationDto {
  @SerializedName("authMethods")
  private List<BasicAuthMethodDto> authMethods = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    IN_REGISTRATION("IN_REGISTRATION"),
    
    DISABLED("DISABLED"),
    
    EXPIRED("EXPIRED"),
    
    INVITED("INVITED"),
    
    DEMO("DEMO");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("uuid")
  private String uuid = null;

  public BasicOrganizationDto authMethods(List<BasicAuthMethodDto> authMethods) {
    this.authMethods = authMethods;
    return this;
  }

  public BasicOrganizationDto addAuthMethodsItem(BasicAuthMethodDto authMethodsItem) {
    if (this.authMethods == null) {
      this.authMethods = new ArrayList<BasicAuthMethodDto>();
    }
    this.authMethods.add(authMethodsItem);
    return this;
  }

   /**
   * Get authMethods
   * @return authMethods
  **/
  @ApiModelProperty(value = "")
  public List<BasicAuthMethodDto> getAuthMethods() {
    return authMethods;
  }

  public void setAuthMethods(List<BasicAuthMethodDto> authMethods) {
    this.authMethods = authMethods;
  }

  public BasicOrganizationDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BasicOrganizationDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public BasicOrganizationDto uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasicOrganizationDto basicOrganizationDto = (BasicOrganizationDto) o;
    return Objects.equals(this.authMethods, basicOrganizationDto.authMethods) &&
        Objects.equals(this.name, basicOrganizationDto.name) &&
        Objects.equals(this.status, basicOrganizationDto.status) &&
        Objects.equals(this.uuid, basicOrganizationDto.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authMethods, name, status, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasicOrganizationDto {\n");
    
    sb.append("    authMethods: ").append(toIndentedString(authMethods)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

