name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]

env:
  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
  GPG_PRIVATE_KEY_ID: ${{ secrets.GPG_PRIVATE_KEY_ID }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
      - name: Publish to Maven Central Repository (OSSRH)
        run: mvn --no-transfer-progress --batch-mode -Dgpg.keyname=$GPG_PRIVATE_KEY_ID -Dgpg.passphrase=$PASSPHRASE clean deploy
